# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orginization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Platoon', models.CharField(max_length=120)),
                ('Company', models.CharField(max_length=120)),
                ('Battalion', models.CharField(max_length=120)),
                ('Brigade', models.CharField(max_length=120)),
                ('Division', models.CharField(max_length=120)),
                ('Corp', models.CharField(max_length=120)),
            ],
        ),
    ]
