# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Record', '0002_orginization'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_record',
            name='Orginization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employee_Record.Orginization'),
        ),
    ]
