# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Record', '0003_employee_record_orginization'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_record',
            name='Rank',
            field=models.CharField(default='CIV', max_length=120),
        ),
    ]
