# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Record', '0004_employee_record_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequierment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Training_Name', models.CharField(max_length=256)),
                ('Training_Duration', models.PositiveSmallIntegerField()),
                ('PV1_Requiered', models.BooleanField()),
                ('PV2_Requiered', models.BooleanField()),
                ('PFC_Requiered', models.BooleanField()),
                ('SPC_Requiered', models.BooleanField()),
                ('CPL_Requiered', models.BooleanField()),
                ('SGT_Requiered', models.BooleanField()),
                ('SSG_Requiered', models.BooleanField()),
                ('SFC_Requiered', models.BooleanField()),
                ('MSG_Requiered', models.BooleanField()),
                ('FIRST_SGT_Requiered', models.BooleanField()),
                ('SGM_Requiered', models.BooleanField()),
                ('CSM_Requiered', models.BooleanField()),
                ('SMA_Requiered', models.BooleanField()),
                ('WO1_Requiered', models.BooleanField()),
                ('CW2_Requiered', models.BooleanField()),
                ('CW3_Requiered', models.BooleanField()),
                ('CW4_Requiered', models.BooleanField()),
                ('CW5_Requiered', models.BooleanField()),
                ('SECOND_LT_Requiered', models.BooleanField()),
                ('FIRST_LT_Requiered', models.BooleanField()),
                ('CPT_Requiered', models.BooleanField()),
                ('MAJ_Requiered', models.BooleanField()),
                ('LTC_Requiered', models.BooleanField()),
                ('COL_Requiered', models.BooleanField()),
                ('BG_Requiered', models.BooleanField()),
                ('MG_Requiered', models.BooleanField()),
                ('LTG_Requiered', models.BooleanField()),
                ('GEN_Requiered', models.BooleanField()),
                ('GA_Requiered', models.BooleanField()),
                ('GS1_Requieres', models.BooleanField()),
                ('GS2_Requieres', models.BooleanField()),
                ('GS3_Requieres', models.BooleanField()),
                ('GS4_Requieres', models.BooleanField()),
                ('GS5_Requieres', models.BooleanField()),
                ('GS6_Requieres', models.BooleanField()),
                ('GS7_Requieres', models.BooleanField()),
                ('GS8_Requieres', models.BooleanField()),
                ('GS9_Requieres', models.BooleanField()),
                ('GS10_Requieres', models.BooleanField()),
                ('GS11_Requieres', models.BooleanField()),
                ('GS12_Requieres', models.BooleanField()),
                ('GS13_Requieres', models.BooleanField()),
                ('GS14_Requieres', models.BooleanField()),
                ('GS15_Requieres', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='orginization',
            name='Training_Requierments',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Employee_Record.TrainingRequierment'),
        ),
    ]
