# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Record', '0006_auto_20160326_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequierment',
            name='Applicable_Orginizations',
            field=models.ManyToManyField(to='Employee_Record.Orginization'),
        ),
    ]
