# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 01:17
from __future__ import unicode_literals

import Employee_Record.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Record', '0007_trainingrequierment_applicable_orginizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_list', Employee_Record.models.ListField()),
            ],
        ),
        migrations.RemoveField(
            model_name='orginization',
            name='Training_Requierments',
        ),
        migrations.RemoveField(
            model_name='trainingrequierment',
            name='Applicable_Orginizations',
        ),
        migrations.AddField(
            model_name='employee_record',
            name='Training',
            field=Employee_Record.models.ListField(default=datetime.datetime(2016, 3, 30, 1, 17, 24, 123945, tzinfo=utc), verbose_name=[2, 2, 2]),
            preserve_default=False,
        ),
    ]
