# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Record', '0008_auto_20160330_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_record',
            name='Training',
        ),
    ]
